---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/bookmarks

- Developer:
    - Github:
          href: https://github.com/liorgadol/

- Router:
    - Homepage:
        - abbr: Main
          href: http://192.168.1.1/

        - abbr: Secondery
          href: http://192.168.1.100          

- Entertainment:
    - YouTube:
          href: https://youtube.com/
