---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- My First Group:
    - qBitorrent:
        href: http://192.168.1.2:8090
        description: Bittorent

- My Second Group:
    - Pihole:
        href: http://192.168.1.2/admin/index.php
        description: Pihole

- My Third Group:
    - Emby:
        href: http://192.168.1.2:8096/web/index.html#!/dashboard.html
        description: Emby Media Server
