---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Home:
    - Pi-Hole:
        icon: https://wp-cdn.pi-hole.net/wp-content/uploads/2016/12/Vortex-R.png.webp
        href: http://192.168.1.2/admin
        ping: http://192.168.1.2/admin
        description: Adblock
        widget:
            type: pihole 
            url: http://192.168.1.2
            key: c983f7211bc18bf8ae43ee9ef7dc6ac0c22ac584d14480779b95c07371de0427

    - Emby:
        icon: emby.png
        href: http://192.168.1.2:8096
        ping: http://192.168.1.2:8096
        description: Media Server
        widget:
              type: emby
              url: http://192.168.1.2:8096
              key: c67372be34ee4ce2a5769ed6a3677661
