---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

background: https://picsum.photos/1600/900.webp/?blur=8&grayscale&random=1
backgroundOpacity: 0.5
theme: dark
color: slate
headerStyle: underlined

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
