---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/service-widgets

- resources:
    cpu: true
    memory: true
    disk: /

- search:
    provider: google
    target: _blank

- Emby:
    icon: emby.png
    href: http://192.168.1.2:8096
    description: Movies & TV Shows
    widget:
      type: emby
      url: http://192.168.1.2:8096
      key: c67372be34ee4ce2a5769ed6a3677661
